/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangedFileCard: typeof import('./../../src/components/ChangedFileCard/ChangedFileCard.vue')['default']
    ChangedSectionsList: typeof import('./../../src/components/ChangedSectionsList/ChangedSectionsList.vue')['default']
    CompactnessSlider: typeof import('./../../src/components/CompactnessSlider/CompactnessSlider.vue')['default']
    ControlsPill: typeof import('./../../src/components/ControlsPill/ControlsPill.vue')['default']
    DetailFooter: typeof import('./../../src/components/DetailFooter/DetailFooter.vue')['default']
    DetailStatTiles: typeof import('./../../src/components/DetailStatTiles/DetailStatTiles.vue')['default']
    DiffModal: typeof import('./../../src/components/DiffModal/DiffModal.vue')['default']
    DistributionBar: typeof import('./../../src/components/DistributionBar/DistributionBar.vue')['default']
    EmptyState: typeof import('./../../src/components/EmptyState/EmptyState.vue')['default']
    FileInfoModal: typeof import('./../../src/components/FileInfoModal/FileInfoModal.vue')['default']
    FilesFilters: typeof import('./../../src/components/FilesFilters/FilesFilters.vue')['default']
    GraphStage: typeof import('./../../src/components/GraphStage/GraphStage.vue')['default']
    HelpPopover: typeof import('./../../src/components/HelpPopover/HelpPopover.vue')['default']
    IconRail: typeof import('./../../src/components/IconRail/IconRail.vue')['default']
    InspectorDetail: typeof import('./../../src/components/InspectorDetail/InspectorDetail.vue')['default']
    InspectorOverview: typeof import('./../../src/components/InspectorOverview/InspectorOverview.vue')['default']
    InspectorPanel: typeof import('./../../src/components/InspectorPanel/InspectorPanel.vue')['default']
    InspectorRowList: typeof import('./../../src/components/InspectorRowList/InspectorRowList.vue')['default']
    InspectorTabs: typeof import('./../../src/components/InspectorTabs/InspectorTabs.vue')['default']
    PathRow: typeof import('./../../src/components/PathRow/PathRow.vue')['default']
    RatioBar: typeof import('./../../src/components/RatioBar/RatioBar.vue')['default']
    SectionLabels: typeof import('./../../src/components/SectionLabels/SectionLabels.vue')['default']
    StarfieldCanvas: typeof import('./../../src/components/StarfieldCanvas/StarfieldCanvas.vue')['default']
    StatusBadge: typeof import('./../../src/components/StatusBadge/StatusBadge.vue')['default']
    ThemeToggle: typeof import('./../../src/components/ThemeToggle/ThemeToggle.vue')['default']
    TopHeader: typeof import('./../../src/components/TopHeader/TopHeader.vue')['default']
  }
}
