/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangedSectionsList: typeof import('./../../src/components/ChangedSectionsList.vue')['default']
    CompactnessSlider: typeof import('./../../src/components/CompactnessSlider.vue')['default']
    ControlsPill: typeof import('./../../src/components/ControlsPill.vue')['default']
    DistributionBar: typeof import('./../../src/components/DistributionBar.vue')['default']
    FilesFilters: typeof import('./../../src/components/FilesFilters.vue')['default']
    GraphStage: typeof import('./../../src/components/GraphStage.vue')['default']
    HelpPopover: typeof import('./../../src/components/HelpPopover.vue')['default']
    IconRail: typeof import('./../../src/components/IconRail.vue')['default']
    InspectorOverview: typeof import('./../../src/components/InspectorOverview.vue')['default']
    InspectorPanel: typeof import('./../../src/components/InspectorPanel.vue')['default']
    LegendList: typeof import('./../../src/components/LegendList.vue')['default']
    RatioBar: typeof import('./../../src/components/RatioBar.vue')['default']
    SectionLabels: typeof import('./../../src/components/SectionLabels.vue')['default']
    ThemeToggle: typeof import('./../../src/components/ThemeToggle.vue')['default']
    TopHeader: typeof import('./../../src/components/TopHeader.vue')['default']
  }
}
